### PR TITLE
Added Desktop Icon and Toogle Shell script plus Phython Program for A…

### PR DESCRIPTION
**Pull request by stefan-neff**
…mbilight > Pushed into your DEV repository

### CODE REVIEW

**Comment by stefan-neff** [comment]
Dont forget to make the toggle-Scrip in /bin executable via chmod +x (rq_light_desktop_amb.sh)

**Comment by JanLahmann** [comment]
@Jas53 , could you please review the changes and approve or comment?

**Review by Jas53 — APPROVED** [review]
changes look good to me

**Comment by JanLahmann** [comment]
@stefan-neff , Thank you for your contribution to RasQberry !

**Pull request merged**
