### PR TITLE
Added desktop icon that opens the Fun-with-Quantum Repo in GitHub.

### PR DESCRIPTION
**Pull request by Jas53**

### CODE REVIEW

**Comment by JanLahmann** [comment]
The examples and serious games from the "Fun with Quantum" repo would be a great addition to RasQberry.
However, they are currently not well suited for a small 4'' display, I'd think.
How would these examples be used on a RasQberry?
Maybe we need specific implementation with a different frontend (other than Jupiter notebooks) to make them usable on RasQberry.

**Comment by Jas53** [comment]
I agree. That is a problem that also needs to be solved. With this PR I wanted to cover issues #44. Maybe I misunderstood the issues.

**Comment by JanLahmann** [comment]
Hi Jasmin, I think now I recall the intention when we opened this issue :-) 
We should put all demos that require a large screen (or vnc connection with high-res) in a separate folder on the desktop.
And add a standard vnc config that saves two virtual screens: one with a mirror of the 4' display, and one with a full DH resolution that can then be used for demos like FwQ and the Qiskit tutorials, etc.

**Comment by JanLahmann** [comment]
before merging this PR, the new issue #63 should be solved, in order to make the FwQ demos usable (which need a high-res screen).

**Review by JanLahmann — APPROVED** [review]

**Pull request merged**
